PARAMETER_KEY_VALUE={\"endDV\":\"EDV\",\"endSV\":\"ESV\",\"sv\":\"SV\",\
\"si\":\"SI\",\
\"ef\":\"EF\",\"er\":\"HR\",\"co\":\"CO\",\"bSA\":\"BSA\",\
\"ci\":\"CI\",\"ES_wall\":\"Min.Wall",\"ED_wall\":\"Max.Wall\",\
\"ED_mass_BSA\":\"EDM/ BSA\",\"ED_frame\":\"ED Frame\",\"ES_frame\":\"ES Frame\",\
\"endDV_BSA\":\"ED vol./BSA\",\"endSAV_BSA\":\"ES vol./BSA\",\"ED_mass\":\"EDM\"}

 PARAMETER_KEY=endDV,endSV,endDV_BSA,endSAV_BSA,sv,si,ef,er,co,bSA,ci,ED_mass,ED_mass_BSA,ES_wall,ED_wall,ED_frame,ES_frame

PARAMETER_KEY_UNITS={\"endDV\":\"ml\",\"endSV\":\"ml\",\"sv\":\"ml\",\
\"si\":\"ml/m²\",\"ef\":\"%\",\"er\":\"bpm\",\"co\":\"L/min\",\"bSA\":\"m²\",\
\"ci\":\"L/min/m²\",\"ES_wall\":\"mm\",\"ED_wall\":\"mm\",\
\"ED_mass_BSA\":\"g/m²\",\"ED_frame\":\"\",\"ES_frame\":\"\",\
\"endDV_BSA\":\"ml/m²\",\"endSAV_BSA\":\"ml/m²\",\"ED_mass\":\"g\"}

 DE_PARAMETER_KEY_VALUE={\"MyocardialMass\":\"Myocardial Mass (gr)\",\"EnhancedMass\":\"Enhanced Mass  (gr)\",\"MyocardialVolume\":\"Myocardial Volume (mm²)\",\"EnhancedVolume\":\"Enhanced Volume (mm²)\",\"PercentageEnhancedVolume\":\"Percentage Enhanced Volume (%)\"}
 DE_PARAMETER_KEY=MyocardialMass,EnhancedMass,MyocardialVolume,EnhancedVolume,PercentageEnhancedVolume
 DE_PARAMETER_KEY_UNITS={\"MyocardialMass\":\"gr\",\"EnhancedMass\":\"gr\",\"MyocardialVolume\":\"mm³\",\"EnhancedVolume\":\"mm³\",\"PercentageEnhancedVolume\":\"%\"}