package com.techvedika.harmonycvi.gateway.constant;

import java.util.HashMap;
import java.util.Map;

public final class CommonConstants {
	public static final String SECURITY_TOKEN="-arc%2Faets%2FDCM4CHEE%2Fwado%3FrequestType%3DWADO%";
	public static final String ACCESS_KEY="accessKey";
	
	public static final String STUDY_ID="studyId";
	public static final String STUDY__ID="study_id";
	public static final String INFO="info";
	public static final String SERIES_ID="seriesId";
	public static final String TWO_CH_SERIESID="twoChSeriesId";
	public static final String FOUR_CH_SERIESID="fourChSeriesId";
	public static final String MESUREMENT_JSON="measurementJson";
	public static final String ID="id";
	public static final String REQUEST = "request";
	public static final String MESUREMENT = "measurementJson";
	public static final String PATIENT_ID = "patientId";
	public static final String CREATION_DATE = "creationDate";
	public static final String LAST_UPDATED_DATE = "lastUpdatedDate";
	public static final String TOOL_TYPE = "toolType";
	public static final String FREE_TEXT = "freeText";
	public static final String LEFT_COUNTER = "leftCounter";
	public static final String X = "x";
	public static final String Y = "y";
	public static final String STSRT_X = "startX";
	public static final String STSRT_Y = "startY";
	public static final String END_X = "endX";
	public static final String END_Y = "endY";
	public static final String START = "start";
	public static final String END = "end";
	public static final String TEXT_BOX = "textBox";
	public static final String BONDING_BOX = "boundingBox";
	public static final String HANDLES = "handles";
	public static final String STUDY_INSTANCE_UID = "studyInstanceUid";
	public static final String STUDY_CLASSIFICATION_DATA = "classification_data";
	public static final String SERIES_INSTANCE_UID = "seriesInstanceUid";
	public static final String SOP_INSTANCE_UID = "sopInstanceUid";
	public static final String FRAME_INDEX = "frameIndex";
	public static final String VISIBLE = "visible";
	public static final String ACTIVE = "active";
	public static final String INVALIDATE = "invalidated";
	public static final String IMAGE_PATH = "imagePath";
	public static final String _ID="_id";
	public static final String TRANSLATION = "translation";
	public static final String VOI = "voi";
	public static final String SCALE = "scale";
	public static final String INVERT = "invert";
	public static final String PIXEL_REPLICATION = "pixelReplication";
	public static final String ROTATION = "rotation";
	public static final String WINDOW_WIDTH = "windowWidth";
	public static final String WINDOW_CENTER = "windowCenter";
	public static final String HIGHLIGHT = "highlight";
	public static final String DRAW_INDEPENDENTLY = "drawnIndependently";
	public static final String MOVES_INDEPENDENTLY = "movesIndependently";
	public static final String ALLOW_OUTSIDE_IMAGE = "allowedOutsideImage";
	public static final String HAS_MOVED = "hasMoved";
	public static final String HAS_BOUNDING_BOX = "hasBoundingBox";
	public static final String LOCKED = "locked";
	public static final String WIDTH = "width";
	public static final String HEIGHT = "height";
	public static final String LEFT = "left";
	public static final String TOP = "top";
	public static final String BOUNDING_BOX = "boundingBox";
	public static final String USER_ID = "userId";
	public static final String USER__ID = "user_id";
	public static final String SERVER_BASE_URL = "server_base_url";
	public static final String AUTHORIZATION = "Authorization";
	public static final String CONTOUR_COMMENT="contour_comment";
	
	public static final String ADDITIONAL_DATA = "additionalData";
	public static final String CREATED_AT = "createdAt";
	public static final String TIME_POINT_ID = "timepointId";
	public static final String MESUREMENT_NUMBER = "measurementNumber";
	public static final String LENGTH = "length";
	public static final String FREE_HAND_LENGTH = "Length";
	public static final String VIEW_PORT = "viewport";
	public static final String IS_FREE_TEXT = "isFreeText";
	public static final String YES = "yes";
	public static final String DATA = "data";
	public static final String RIGHT_COUNTER = "rightCounter";
	public static final String WALL = "wall";
	public static final String IS_AI_PRECCESSED = "isAIProccessed";
	public static final String LV = "lv";
	public static final String RV = "rv";
	public static final String AI_STUDY_URL = "AI_STUDY_URL";
	public static final String AI_STUDY_URL2 = "AI_STUDY_URL2";
	public static final String UPLOAD_STUDY_URL = "UPLOAD_STUDY_URL";
	public static final String COORDINATES = "coordinates";
	public static final String LINES = "lines";
	public static final String COMMON_DATA = "commonData";
	public static final String INSTANCE_ARRAY = "instanceArray";
	public static final String SHA_256 = "SHA-256";
	public static final String EMAIL = "email";
	public static final String PASSWORD = "password";
	public static final String COLOR = "color";
	public static final String RV_COLOR = "RV_COLOR";
	public static final String LV_COLOR = "LV_COLOR";
	public static final String WALL_COLOR = "WALL_COLOR";
	public static final String PROPERTIES_FILE_PATH ="/opt/wildfly/standalone/configuration/application.properties";
	public static final String PARAMETER_PROPERTIES_FILE_PATH ="/opt/wildfly/standalone/configuration/parameter.properties";
	public static final String RADIAL_STRAIN = "radialStrain";
	public static final String PARAMETER_REFERENCE = "parameterReference";
	public static final String MAX = "max";
	public static final String MIN = "min";
	public static final String VALUE = "value";
	public static final String SHORT_NAME = "shortName";
	public static final String LONG_NAME = "longName";
	public static final String UNITS = "units";
	public static final String ED_FRAME = "ED_frame";
	public static final String ES_FRAME = "ES_frame";

	public static final String SELECTED_BOOKMARK = "selectedBookmarkId";

	public static final String PARAMETER = "parameter";
	public static final String SEGMENTS = "segments";
	public static final String FREE_HAND_MOUSE = "FreehandMouse";
	public static final String PARAMETER_KEY = "PARAMETER_KEY";
	public static final String PARAMETER_KEY_VALUE = "PARAMETER_KEY_VALUE";
	public static final String PARAMETER_KEY_UNITS = "PARAMETER_KEY_UNITS";
	public static final String COORDINATES_TYPE = "coordinateType";
	public static final String IS_SEGMENTS = "isSegments";
	public static final String MID_MYO = "mid_myo";
	public static final String MID_MYO_COLOR = "MID_MYO_COLOR";
	public static final String GRAPH = "graph";
	public static final String COMPUTED_SERIES = "computed_series";
	public static final String WALL_MOTATION = "wallMotation";
	public static final String SUMMARY = "summary";
	public static final String ENHANCEMENT_PATTERN = "enhancementPattern";
	static Map<String,String> PARAMETER_CONSTANT = new HashMap<String, String>();
	public static final String STATUS="status";
	public static final String STUDY_ANNOTATION = "studyAnnotation";
	public static final Object INSTANCE_ID = "instanceId";
	public static final String CONTOUR = "contour";
	public static final String PHASE_SOP_INSTANCE_UID = "phasesopInstanceUid";
	public static final String TYPE = "type";
	public static final String PATIENT_WEIGHT = "patient_weight";
	public static final String PATIENT_HEIGHT = "patient_height";
	public static final String ORG_ID = "orgId";
	public static final String ORG__ID = "org_id";
	public static final String IMG_COUNT = "img_count";
	public static final String IMAGE_PLANE = "ImagePlane";
	public static final String SEQUENCE_TYPE = "SequenceType";
	public static final String SEG_INFORMATION = "seg_information";
	public static final String SEGMENT_TYPE = "segment_type";
	public static final String SERIES_ARRAY = "series_array";
	public static final String SA_TAGS = "SA_tags";
	public static final String QFLOW_TAGS = "Qflow_tags";
	public static final String SEND_MULTIPLE = "sendMultiple";
	public static final String STATUS_CODE = "status_code";
	public static final String COMMENT = "comment";
	public static final String REPROCESS = "reprocess";
	public static final String TAG_INFO = "tag_info";
	public static final String IMAGE_TYPE = "imageType";
	public static final String TAGS_DATA = "tagsData";
	public static final String IMAGE_DATA = "imageData";
	public static final String SERIES_TYPE = "seriesType";
	public static final String QFLOW = "Qflow";
	public static final String GLS = "GLS";
	public static final String ATRIAL = "ATRIAL";
	public static final String DE = "DE";
	public static final String DICOM_COUNT = "dicomFilesCount";
	public static final String JWT_TOKEN = "jwtToken";
	public static final String S3_DIRECTORY = "s3_directory";
	public static final String S3_STUDY_LINK = "s3FileName";
	public static final String UPLOADTOS3SWITCH = "UPLOAD_TO_S3";
	
	//AWS S3
	//Also Hardcoded these values in org.dcm4chee.arc.delete.impl
	public static final String S3_PDF_LINK = "s3FileName";
	public static final String AWSACCESSKEY = "AWS_ACCESS_KEY";
	public static final String AWSSECRETACCESSKEY = "AWS_SECRET_ACCESS_KEY";
	public static final String AWSBUCKETNAME = "AWS_BUCKET_NAME";
	public static final String STUDYUPLOADBUCKETNAME = "S3UPLOAD_BUCKET_NAME";
	public static final String T1Map = "T1Map";
	public static final String T2Map = "T2Map";
	public static final String ECVMap = "ECV";
	public static final String T2Star = "T2*";

	public static final String URL = "url";
	public static final String REGION = "REGION";
	public static final String APIKEY = "APIKEY";
	public static final String FILENAME = "FILENAME";
	public static final String BUCKET = "BUCKET";
	public static final String REQURL = "REQURL";
	public static final String EXPMINS = "EXPMINS";
	
	public static final String TWOCH_SERIES_ID="twoChSeriesInstanceUID";
	public static final String FOURCH_SERIES_ID="fourChSeriesInstanceUID";
	public static final String DE_SERIES_ID="DelayedSeriesInstanceUID";
	public static final String SHORT_AXIS_CONTOUR="ShortAxisContourJson";
	public static final String SERIES_LIST = "seriesIdList";
	public static final String NAME = "name";
	public static final Object DESCRIPTION = "description";
	public static final String PROPGATION_INFO = "propagationInfo";
	public static final String SHORT_AXIS_DATA = "shortaxisData";
	
	public static final String COMBINED_SERIES_IDS = "combinedSeriesIds";
	public static final String UPDATE_SERIES_TYPES = "updateSeriesTypes";
	public static final String CONTOUR_DATA ="contourData";
	public static final String BOOKMARK = "bookmark";
	public static final String BOOKMARK_ID = "bookmark_id";
	public static final String SA_PARAMETER="saParams";
	public static final String VOLUME_INFO="volume_info";
	public static final long SUPER_ADMIN_ID = 1;
	public static final String PRE_SIGNED_URL="preSignedUrl";
	public static final String UPLOAD_TYPE = "uploadType";
	public static final String UPLOAD_TYPE_SINGLE = "single";
	public static final String UPLOAD_TYPE_MULTIPART = "multipart";
	public static final String APPLICATION_JSON = "application/json";
	
	public static final String DE_PARAMETER_KEY_VALUE = "DE_PARAMETER_KEY_VALUE";
	public static final String DE_PARAMETER_KEY_UNITS = "DE_PARAMETER_KEY_UNITS";
	public static final String DE_PARAMETER_KEY = "DE_PARAMETER_KEY";
	public static final String VERSION_VIEWER = "viewer_version";
	public static final String VERSION_ADMIN= "admin_version";
	public static final HashMap<String,String> AI_PROCESS_STATUS = new HashMap<>();
	
	public static final String AWS_BASE_URL ="https://cvi-report.s3.ap-south-1.amazonaws.com/";

	static {
		PARAMETER_CONSTANT.put("endDV","End Diastolic Volume (ml)");
		PARAMETER_CONSTANT.put("endSV","End Systolic Volume (ml)");
		PARAMETER_CONSTANT.put("sv","Stroke Volume (ml)");
		PARAMETER_CONSTANT.put("ef","Ejection Fraction (%)");
		PARAMETER_CONSTANT.put("er","Heart Rate (bpm)");
		PARAMETER_CONSTANT.put("co","Cardiac Output (L/min)");
		PARAMETER_CONSTANT.put("bSA","Body Surface Area (m²)");
		PARAMETER_CONSTANT.put("ci","Cardiac Index");
		PARAMETER_CONSTANT.put("minWT","Minimum Wall Thickness");
		PARAMETER_CONSTANT.put("maxWT","Maximum Wall Thickness");
		AI_PROCESS_STATUS.put("Short Axis View", "VentricleAssessment");
		AI_PROCESS_STATUS.put("Q_flow_process", "Qflow");
		AI_PROCESS_STATUS.put("GLS", "GLS");
		AI_PROCESS_STATUS.put("DE", "DE");

	}
}